
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urnatela;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import urna.botao;
import urna.conexao;
import static urna.conexao.statement;

/**
 *
 * @author CAMPOI
 */
public class telaurna extends javax.swing.JFrame {

    private int confi2rma;

    /**
     * Creates new form telaurna
     */
    public telaurna() {
        initComponents();
    }

    
    public String numero = "", 
    numcand = "";
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbf = new javax.swing.JLabel();
        lb4 = new javax.swing.JButton();
        lb7 = new javax.swing.JButton();
        lb0 = new javax.swing.JButton();
        lb2 = new javax.swing.JButton();
        lb5 = new javax.swing.JButton();
        lb8 = new javax.swing.JButton();
        lb3 = new javax.swing.JButton();
        lb6 = new javax.swing.JButton();
        lb9 = new javax.swing.JButton();
        lb1 = new javax.swing.JButton();
        corrige = new javax.swing.JButton();
        confirma = new javax.swing.JButton();
        branco = new javax.swing.JButton();
        candinome = new javax.swing.JLabel();
        lbvoto1 = new javax.swing.JLabel();
        lbvoto2 = new javax.swing.JLabel();
        lbvoto3 = new javax.swing.JLabel();
        candicargo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbf.setBorder(new javax.swing.border.MatteBorder(null));

        lb4.setBackground(new java.awt.Color(0, 0, 0));
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setText("4");
        lb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb4MouseClicked(evt);
            }
        });

        lb7.setBackground(new java.awt.Color(0, 0, 0));
        lb7.setForeground(new java.awt.Color(255, 255, 255));
        lb7.setText("7");
        lb7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb7MouseClicked(evt);
            }
        });

        lb0.setBackground(new java.awt.Color(0, 0, 0));
        lb0.setForeground(new java.awt.Color(255, 255, 255));
        lb0.setText("0");
        lb0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb0MouseClicked(evt);
            }
        });

        lb2.setBackground(new java.awt.Color(0, 0, 0));
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("2");
        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2MouseClicked(evt);
            }
        });
        lb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb2ActionPerformed(evt);
            }
        });

        lb5.setBackground(new java.awt.Color(0, 0, 0));
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setText("5");
        lb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb5MouseClicked(evt);
            }
        });

        lb8.setBackground(new java.awt.Color(0, 0, 0));
        lb8.setForeground(new java.awt.Color(255, 255, 255));
        lb8.setText("8");
        lb8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb8MouseClicked(evt);
            }
        });

        lb3.setBackground(new java.awt.Color(0, 0, 0));
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setText("3");
        lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3MouseClicked(evt);
            }
        });

        lb6.setBackground(new java.awt.Color(0, 0, 0));
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setText("6");
        lb6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb6MouseClicked(evt);
            }
        });
        lb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb6ActionPerformed(evt);
            }
        });

        lb9.setBackground(new java.awt.Color(0, 0, 0));
        lb9.setForeground(new java.awt.Color(255, 255, 255));
        lb9.setText("9");
        lb9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb9MouseClicked(evt);
            }
        });

        lb1.setBackground(new java.awt.Color(0, 0, 0));
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("1");
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb1MouseClicked(evt);
            }
        });
        lb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb1ActionPerformed(evt);
            }
        });

        corrige.setText("CORRIGE");
        corrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corrigeMouseClicked(evt);
            }
        });
        corrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigeActionPerformed(evt);
            }
        });

        confirma.setBackground(new java.awt.Color(0, 153, 102));
        confirma.setText("CONFIRMA");
        confirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmaMouseClicked(evt);
            }
        });
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        branco.setBackground(new java.awt.Color(255, 255, 255));
        branco.setText("BRANCO");
        branco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brancoMouseClicked(evt);
            }
        });

        candinome.setText("Nome do candidato");

        lbvoto1.setBackground(new java.awt.Color(255, 255, 255));
        lbvoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvoto1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbvoto2.setBackground(new java.awt.Color(255, 255, 255));
        lbvoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvoto2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbvoto3.setBackground(new java.awt.Color(255, 255, 255));
        lbvoto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvoto3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        candicargo.setText("Cargo do candidato");

        jList1.setBorder(new javax.swing.border.MatteBorder(null));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "244 - Terry", "349 - Manigold", "654 - Regulus", "658 - Albafica", "687 - Dohko" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("URNA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(66, Short.MAX_VALUE)
                        .addComponent(lbvoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbvoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbvoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(candicargo)
                                    .addComponent(candinome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lbf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(branco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corrige)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branco)
                            .addComponent(confirma)
                            .addComponent(corrige))
                        .addGap(439, 439, 439))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(candinome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(candicargo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbvoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbvoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbvoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb2ActionPerformed

    private void lb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb1ActionPerformed

    private void lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseClicked
        // TODO add your handling code here: 
        String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
       
         numero  = "1";    
    mostraNum();         
 
    }//GEN-LAST:event_lb1MouseClicked

    private void lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
         
          numero  = "2";    
    mostraNum();   
    }//GEN-LAST:event_lb2MouseClicked
int voto=0, id=0;
 private void soma(){
        String sql = "Update tb04_eleicao set tb04_voto = tb04_voto +1 where tb04_id_eleicao =" + numcand;
          try{
       
        conexao objetoBD = new conexao();
        objetoBD.conectar();
        int qtdreg = objetoBD.runSQL(sql);
        objetoBD.desconectar();
       
        }   
        catch (Exception e){
             System.out.println(e.getMessage());
         }        
    }       
      private void pegaCandidato(String codi)
    {
       try     
       { 
           
        String sql = "SELECT * FROM tb04_eleicao join tb03_candidato on tb04_cpf=tb03_cpf join tb02_cargo on tb02_cod_cargo=tb04_cod_cargo \n where tb04_id_eleicao = " + codi;
        
        conexao banco = new conexao();
        
        banco.conectar();
        
        ResultSet resultSet = statement.executeQuery(sql);  
        
        while (resultSet.next())
            {
              candinome.setText(resultSet.getString("tb03_nome"));   
              candicargo.setText(resultSet.getString("tb02_nome"));  
              Image img = Toolkit.getDefaultToolkit().createImage(resultSet.getBytes("tb03_foto"));
              ImageIcon foto = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbf.getWidth(), lbf.getHeight(), Image.SCALE_DEFAULT));
              lbf.setIcon(foto);  
              voto=resultSet.getInt("tb04_voto");
             id=resultSet.getInt("tb04_id_eleicao");
            }
        
        banco.desconectar();
        resultSet.close();
        statement.close();  
        }
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }
              
    private void lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
      
          numero  = "3";    
    mostraNum();   
    }//GEN-LAST:event_lb3MouseClicked

    private void lb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb4MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
           numero  = "4";    
    mostraNum();
    }//GEN-LAST:event_lb4MouseClicked

    private void lb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb5MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
         numero  = "5";    
    mostraNum();
          //jlabelsexo
    }//GEN-LAST:event_lb5MouseClicked

    private void lb6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb6MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
         numero  = "6";    
    mostraNum();
    }//GEN-LAST:event_lb6MouseClicked

    private void lb7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb7MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
          numero  = "7";    
    mostraNum();
    }//GEN-LAST:event_lb7MouseClicked

    private void lb8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb8MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
       numero  = "8";    
    mostraNum();
    }//GEN-LAST:event_lb8MouseClicked

    private void lb9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb9MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
           numero  = "9";    
    mostraNum();
    }//GEN-LAST:event_lb9MouseClicked

    private void lb0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb0MouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\Tecla.wav";
	botao p = new botao();
          p.Som(caminho);
          
              numero  = "0";    
    mostraNum(); 
    }//GEN-LAST:event_lb0MouseClicked

    private void confirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmaMouseClicked
        // TODO add your handling code here:
          String caminho = "E:\\2022\\Recursos Urna\\urna.wav";
	botao p = new botao();
          p.Som(caminho);
          
      
         if(!candinome.getText().equals("Nome do candidato")){   JOptionPane.showMessageDialog(
    null, "Voto computado!");   
         }
         else{  
                   
         JOptionPane.showMessageDialog(
    null, "Votou no nada!");   
         }
        
    }//GEN-LAST:event_confirmaMouseClicked
    
    private void lb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb6ActionPerformed

    private void corrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corrigeActionPerformed

    private void corrigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corrigeMouseClicked
        // TODO add your handling code here:
        lbvoto1.setText("");
      lbvoto2.setText("");
      lbvoto3.setText("");
      
      lbf.setIcon(null);
      candinome.setText("Nome do candidato");
      candicargo.setText("Cargo do candidato");
    }//GEN-LAST:event_corrigeMouseClicked

    private void brancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brancoMouseClicked
        {
    JOptionPane.showMessageDialog(
    null, "Voto Branco!");    
    }    }//GEN-LAST:event_brancoMouseClicked

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        soma();
    }//GEN-LAST:event_confirmaActionPerformed

      

    private void mostraNum(){
        
        if(lbvoto1.getText().equals("")){lbvoto1.setText(numero);
        
        
        
    }
        else 
             if(lbvoto2.getText().equals("")){lbvoto2.setText(numero);
    }
        else
         if(lbvoto3.getText().equals("")){lbvoto3.setText(numero);
         
         numcand = (lbvoto1.getText()+ lbvoto2.getText()+lbvoto3.getText());
           pegaCandidato(numcand);
//         criaCandidato();
         }
    }
    
            
      private void criaCandidato(){
    {
        
        {
     ImageIcon image = new ImageIcon(this.getClass().getResource("/img/candidato_" +numcand+ ".jpg"));
     Image img = image.getImage().getScaledInstance(lbf.getWidth(), lbf.getHeight(), Image.SCALE_SMOOTH);
     lbf.setIcon(new ImageIcon(img));           

     switch(numcand){
            
     case "001":
          candinome.setText("Dohko - PP ");
          candicargo.setText("Presidente");
     break;
            
     case "002":
          candinome.setText("Albafica - PT");
          candicargo.setText("Presidente");
     break;
                
     case "003":
          candinome.setText("Manigold - MDB ");
          candicargo.setText("Vice-presidente");
     break;
     
     case "004":
          candinome.setText("Regulus - PP ");
          candicargo.setText("Presidente");
     break;
 }}}}
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaurna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaurna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton branco;
    private javax.swing.JLabel candicargo;
    private javax.swing.JLabel candinome;
    private javax.swing.JButton confirma;
    private javax.swing.JButton corrige;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lb0;
    private javax.swing.JButton lb1;
    private javax.swing.JButton lb2;
    private javax.swing.JButton lb3;
    private javax.swing.JButton lb4;
    private javax.swing.JButton lb5;
    private javax.swing.JButton lb6;
    private javax.swing.JButton lb7;
    private javax.swing.JButton lb8;
    private javax.swing.JButton lb9;
    private javax.swing.JLabel lbf;
    private javax.swing.JLabel lbvoto1;
    private javax.swing.JLabel lbvoto2;
    private javax.swing.JLabel lbvoto3;
    // End of variables declaration//GEN-END:variables

    private void MOSTRACA(String numcand) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
